services:
  data-preparation:
    image: data-preparation:latest
    build: .
    command: snakemake --cores 10 report.txt
    volumes:
      - type: bind
        source: ./database
        target: /snakemake/database
      - type: bind
        source: ./cities
        target: /snakemake/citiesw